# Generated by Django 3.2.5 on 2021-07-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('is_send', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
